plugins {
   id("java")
   id("io.papermc.paperweight.userdev") version("2.0.0-beta.19")
   id("com.gradleup.shadow") version "9.3.0"
}

group = 'com.ontey'
version = '1.0'

repositories {
   mavenCentral()

   maven {
      name = "papermc-repo"
      url = "https://repo.papermc.io/repository/maven-public/"
   }

   maven {
      url = "https://jitpack.io"
   }
}

// Yes I use shadowJar to copy the jar...
tasks.shadowJar {
   relocate("com.ontey.api", "com.ontey.serverCore.lib.api")

   destinationDirectory = file("C:\\Users\\klett\\Documents\\Minecraft\\Servers\\TestServer\\plugins")
   archiveFileName = "ServerCore-${version}.jar"
}

dependencies {
   // Paper
   compileOnly("io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT")

   // Paperweight (NMS)
   paperweight.paperDevBundle("1.21-R0.1-SNAPSHOT")

   // OnteyAPI
   implementation("com.github.Ontey6:OnteyAPI:1.0.2")

   // lombok
   compileOnly("org.projectlombok:lombok:1.18.42")
   annotationProcessor("org.projectlombok:lombok:1.18.42")
   testCompileOnly("org.projectlombok:lombok:1.18.42")
   testAnnotationProcessor("org.projectlombok:lombok:1.18.42")
}

def targetJavaVersion = 21
java {
   def javaVersion = JavaVersion.toVersion(targetJavaVersion)
   sourceCompatibility = javaVersion
   targetCompatibility = javaVersion
   if(JavaVersion.current() < javaVersion)
      toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
   options.encoding = 'UTF-8'
   options.release.set(targetJavaVersion)
}

processResources {
   def props = [version: version]
   inputs.properties props
   filteringCharset = 'UTF-8'
   filesMatching('plugin.yml') {
      expand props
   }
}
